<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Parth" name="com.bank.testsuite.BankTest" tests="5" failures="1" timestamp="2023-07-16T15:14:19 BST" time="48.902" errors="0">
  <testcase name="customerShouldLoginAndLogoutSuceessfully" time="9.215" classname="com.bank.testsuite.BankTest"/>
  <system-out/>
  <testcase name="customerShouldWithdrawMoneySuccessfully" time="10.688" classname="com.bank.testsuite.BankTest">
    <failure type="java.lang.AssertionError" message="Transaction Successful is not displayed expected [Transaction Successful] but found [Transaction Failed. You can not withdraw amount more than the balance.]">
      <![CDATA[java.lang.AssertionError: Transaction Successful is not displayed expected [Transaction Successful] but found [Transaction Failed. You can not withdraw amount more than the balance.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.bank.testsuite.BankTest.customerShouldWithdrawMoneySuccessfully(BankTest.java:175)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- customerShouldWithdrawMoneySuccessfully -->
  <system-out/>
  <testcase name="bankManagerShouldOpenAccountSuccessfully" time="9.269" classname="com.bank.testsuite.BankTest"/>
  <system-out/>
  <testcase name="customerShouldDepositMoneySuccessfully" time="10.244" classname="com.bank.testsuite.BankTest"/>
  <system-out/>
  <testcase name="bankManagerShouldAddCustomerSuccessfully" time="9.486" classname="com.bank.testsuite.BankTest"/>
  <system-out/>
</testsuite> <!-- com.bank.testsuite.BankTest -->
